# Generated by Django 5.1.2 on 2024-12-22 22:02

import django.db.models.deletion
import patterns.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern_type', models.CharField(choices=[('separated', 'Separated Sweater Pieces')], default='separated', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeparatedSweater',
            fields=[
                ('pattern_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patterns.pattern')),
                ('sweater_file', models.FileField(upload_to=patterns.models.sweater_upload_path)),
            ],
            bases=('patterns.pattern',),
        ),
        migrations.CreateModel(
            name='Swatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('stitches', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('needle_size', models.FloatField()),
                ('pattern', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swatch', to='patterns.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swatches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Torso_Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('ribbing', models.CharField(blank=True, choices=[('thin', 'Thin'), ('normal', 'Normal'), ('thick', 'Thick')], default=None, max_length=6, null=True)),
                ('taper_offset', models.FloatField(default=0)),
                ('taper_hem', models.FloatField(default=0)),
                ('neck_offset_width', models.FloatField(default=0)),
                ('neck_offset_height', models.FloatField(default=0)),
                ('neck_depth', models.FloatField(default=0)),
                ('sweater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='torso_projection', to='patterns.separatedsweater')),
            ],
        ),
        migrations.CreateModel(
            name='Sleeve_Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('ribbing', models.CharField(blank=True, choices=[('thin', 'Thin'), ('normal', 'Normal'), ('thick', 'Thick')], default=None, max_length=6, null=True)),
                ('taper_offset', models.FloatField(default=0)),
                ('taper_hem', models.FloatField(default=0)),
                ('taper_style', models.CharField(choices=[('both', 'Both'), ('top', 'Top'), ('bottom', 'Bottom')], default='both', max_length=6)),
                ('neck_offset_width', models.FloatField(default=0)),
                ('neck_offset_height', models.FloatField(default=0)),
                ('neck_depth', models.FloatField(default=0)),
                ('sweater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_projection', to='patterns.separatedsweater')),
            ],
        ),
    ]
